spring:
  application:
    name: login

jwt:
  accessToken:
    secret: ${JWT_ACCESS_SECRET_KEY}
    expiration: 1800000  # 30분
  refreshToken:
    secret: ${JWT_REFRESH_SECRET_KEY}
    expiration: 604800000  # 7일
